trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'

pool: DEFRA-COMMON-ubuntu2004-SSV3

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK 8'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - script: dotnet test src/EPR.RegistrationValidation.IntegrationTests/EPR.RegistrationValidation.IntegrationTests.csproj --filter "TestCategory=Integration"
    displayName: 'Run integration tests'
