variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'registrationvalidationrepository'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'registrationvalidationrepository'
  serviceName: 'prdrwdwebfa1404'
