variables:
- group: ServiceConnection-PRD1
- name: docker.imageName
  value: 'registrationvalidationrepository'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'registrationvalidationrepository'
- name: serviceName
  value: 'prdrwdwebfa1404'
